### PR TITLE
Improve Texas Instruments DSBGA and BGA footprints

### PR DESCRIPTION
**Pull request by evanshultz**
I initially set out to create the DSBGA package for [LMC555](http://www.ti.com/lit/ds/symlink/lmc555.pdf), but I found some other things in related footprints to improve.

First, the existing "Junior" footprint was marked "DSBGA" but it isn't. DSBGA is a different type of footprint and this one doesn't fall into the DSBGA family. So I renamed it and updated the description.

For all the DSBGA footprints:
- Prefixed `Texas_` to their file names since they appear to be specific to Texas Instruments (TI)
- Improved the footprint description

Next, I discovered that TI prefers the NSMD style of pad on page 6 at http://www.ti.com/lit/an/snva009ag/snva009ag.pdf. One footprint had the suffix `Dia0.25mm` and didn't use this pad style. So I created a variant of that footprint using the NSMD pad style. This creates a KLC violation since the mask size over the pad size is fixed. I should assume that this is OK since a user dropping this footprint on their board should know there are requirements for BGAs and a user with general skills and board design won't be used BGAs (?). Anyway, it seems to be we're best off with TI's recommended footprint as the default even if other variants are available.

Finally, I created my new footprint.

Images:
image
image

Questions:
1. Should the NSMD pad style be the default? If so, I will do that to the 12 bump footprint and add this in the description of all affected footprints.
1. These parts aren't named with the bump array pattern like TI. For example, the 12 bump footprint is named "3x4" but TI calls it "4x3". See page 4 of the last doc linked above. Should we use the TI array designation or keep the existing naming?
1. The DSBGA-12 part is marked as having a 1.86x1.36mm package size but I haven't found that datasheet (DSBGA-10 parts seem to be that size). http://www.ti.com/packaging/docs/searchtipackages.tsp?packageName=DSBGA shows a number of 12 bump 3x4 packages with 0.5mm pitch, but other package dimensions aren't given on those drawings. Can anyone help me find a part with that bump count, bump array, and package size?
1. The ref des on F.Fab sticks out from under the package body on many of these footprints already. Is that OK and can be left that way, or was it missed and I should shrink them?

### CODE REVIEW

**Comment by evanshultz** [comment]
I was looking more at the Microstart Junior BGA packages. Some info:
- http://www.ti.com/lit/wp/ssyz015b/ssyz015b.pdf (see padstack info on page 10 + Figure 8)
- http://www.ti.com/lit/an/szza005/szza005.pdf
- http://www.ti.com/lit/ml/scet004/scet004.pdf
- http://www.ti.com/lit/ml/mpbg618a/mpbg618a.pdf
- http://www.ti.com/lit/ds/symlink/txb0104.pdf

The second link shows that NSMD is prefered for MicroStar Junior BGA as well, similar to question #1 above.

I also don't see a list of all packages in this family (the family docs don't mention the 12 ball at all), but I think it behooves us to include the pattern in the footprint name (adding `4x3` as I've done above) since the DSBGA footprints do have the same bump quantity but in different patterns. I asked at https://e2e.ti.com/support/interface/voltage_level/f/391/p/607023/2254179#2254179.

**Comment by SchrodingersGat** [comment]
1. Thanks for the in-depth research you have done here. As the datasheet says that NSMD is preferred, I would certainly use that layout.

2. For outer dimension we should always specify `WxH` so preference this over the Ti convention

3. 

4. You can shrink the Refdes to fit inside outline, and also rotate if the part is taller than it is wide.

**Comment by evanshultz** [comment]
1. Updated to use NSMD pad style, with the MicroStar following page 10 of the doc above. I didn't do the one that suffixed by `Dia0.25mm` since it clearly violates TI's recommendations? Delete that footprint?
2. OK. They're all named as such.
3. [TXS0104](http://www.ti.com/lit/ds/symlink/txs0104e.pdf) and [TS5A26542](http://www.ti.com/lit/ds/scds232e/scds232e.pdf) show 1.9x1.9mm on the front page of the datasheet, but the package drawing shows 1.36x1.86mm. Asked at https://e2e.ti.com/support/interface/voltage_level/f/391/t/613737.
4. F.Fab refdes text shrunk and rotated, if needed, to fit better.

I also made the following fixes:
1. Silk on DSBGA-12 and MicroStar now look like silk on DSBGA-8
1. Courtyard clearance is now 1.0mm on all footprints as specified by KLC
1. Updated the MicroStar Junior footprint name to match the other ones, which follows this paradigm: `Texas_<description>-<pad number>_<WxH pad array>_<XxY dimensions>_Pitch<pitch>mm`.

**Comment by evanshultz** [comment]
And I just added a new footprint in this family. Datasheet: http://www.ti.com/lit/ds/symlink/tlv320aic23b.pdf

Image of all footprints:
image

**Comment by evanshultz** [comment]
I believe all remaining KLC violations are due to using the NSMD pad definition, so they should be OK.

I also didn't include the `Dia0.25mm` footprint above since it looks wrong. Neither the pad style nor the stencil design used is recommended.

**Comment by evanshultz** [comment]
The big MicroStar footprint actually has 80 pads, since C3 is omitted on a 9x9 pattern, so updated as such.

**Comment by evanshultz** [comment]
New image for 80 pin BGA:
image

@SchrodingersGat 
Are you able to review? Should the `Dia0.25mm` footprint be removed since it uses non-recommended pads?

**Comment by SchrodingersGat** [comment]
Are the paste pads supposed to be square? The DSBGA parts all have square pads on the Paste layer

**Comment by evanshultz** [comment]
@SchrodingersGat 
Thanks for reviewing!

Yep, they are. Weird, huh? Here is page 29 of the LMC555 datasheet I linked above:
image

**Comment by SchrodingersGat** [comment]
Cool! Let's make a mental note to revisit these and convert them to rounded-rectangle once v5 is released (as this feature isn't in stable branch yet). Thanks for your work on this.

**Pull request merged**
