### PR TITLE
Correct MicroStar Junior padstacks (mask and paste)

### PR DESCRIPTION
**Pull request by evanshultz**
As discussed at https://github.com/KiCad/Housings_BGA.pretty/pull/18, the NSMD pad style was a bit incorrect. Here is the relevant section of the [TI doc](http://www.ti.com/lit/wp/ssyz015b/ssyz015b.pdf):
image

I was thinking radius, I guess, and make the mask 0.1mm oversize. Since the drawing is the diameter, I should have used 0.05mm. I fixed that.

Also, the stencil openings can be the same as the pad to 0.05mm oversize. Not 0.1mm oversize like they were. I shrunk those to the same size as well.

That's it!

### CODE REVIEW

**Comment by evanshultz** [comment]
Can I get a review please? This should be a quick one.

**Comment by poeschlr** [comment]
Why do you set the solder mask clearance in the pads instead of in the footprint settings?
If you do it this way and it needs to be changed for some reason one has to either use a text editor or change all pads one by one in the footprint editor.

The pin 1 marker dot is below the part. This could create problems for reflow soldering.

**Comment by evanshultz** [comment]
@poeschlr To be perfectly honest, I'd only done this per-pad in the past and didn't explore that option for the entire footprint before. Footprints are updated now.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
