### PR TITLE
removed Windows endlines

### PR DESCRIPTION
**Pull request by Shackmeister**
not sure if this is accepted though :)

### CODE REVIEW

**Comment by Shackmeister** [comment]
does anybody know why the description of BGA 9 is stolen from BGA 16?

**Comment by Shackmeister** [comment]
bga

**Comment by SchrodingersGat** [comment]
@Shackmeister why have you moved the second RefDes on the F.Fab layer? This should be placed @ (0,0) (center of the footprint) by default...

**Comment by Shackmeister** [comment]
@SchrodingersGat I thought it was supposed to be visible, but should it always be on 0,0?

**Comment by SchrodingersGat** [comment]
The RefDes on the **Silkscreen** layer must be visible after placement. The RefDes on the **Fabrication** layer should be placed inside the component, e.g. at (0,0) in this case.

**Comment by Shackmeister** [comment]
Ah ok I will fix this and push it

**Comment by Shackmeister** [comment]
bga
should be fixed now

**Comment by SchrodingersGat** [comment]
Looks great :)

**Pull request merged**
