### PR TITLE
Tsc2046

### PR DESCRIPTION
**Pull request by Misca1234**
This is push for TSC2046

Datasheet
http://www.ti.com/lit/ds/symlink/tsc2046.pdf

Main: TSC2046IPW
Alias TSC2046IPWG4, TSC2046IPWR, TSC2046IPWRG4

Main TSC2046IRGVR
Alias TSC2046IRGVRRG4, TSC2046IRGVT

Main TSC2046IZQCR

kicad-library branch
https://github.com/KiCad/kicad-library/pull/1491

Housings_BGA.pretty branch
https://github.com/KiCad/Housings_BGA.pretty/pull/18

packages3D branch
https://github.com/KiCad/packages3D/pull/107

bild

bild

bild

bild

### CODE REVIEW

**Comment by evanshultz** [comment]
@Misca1234 
Please use the NSMD pad style discussed at https://github.com/KiCad/Housings_BGA.pretty/pull/17.

**Comment by Misca1234** [comment]
The BGA foot print have been renamed and modified into this

bild

bild

bild

bild

bild

**Comment by evanshultz** [comment]
@Misca1234 
Review comments:
1. Please include a moret robust description. See the existing MicroStar Junior parts at the PR I linked above.
2. Move the F.Fab ref des from (0.1,0.1) to right at (0,0).
3. Similar, move the ref des in silk and package name in F.Fab at 0 to the x axis.
4. Use the pin 1 mark and corner silk marks from the aforementioned PR.
5. Use the NSMD pad style defined by TI and used in the other MicroStar Junior footprints.
6. Fully describe the footprint by it's name. Ball pattern, size, pitch, etc. https://github.com/KiCad/Housings_BGA.pretty/blob/master/Texas_MicroStar_Junior_BGA-80_9x9_5.0x5.0mm_Pitch0.5mm.kicad_mod is a good reference for many of the items above.

Thanks for contributing, and I look forward to merging this PR soon!

**Comment by Misca1234** [comment]
Something like this ?

bild

bild

**Comment by evanshultz** [comment]
@Misca1234 
Sorry for the delay. Looking good!

A few things:
- Item 2 above still not done; put F.Fab refdes at origin.
- For item 3 above, the footprint name isn't at 0 on X axis.
- The footprint name and description show 49 balls, but because one is missing there are only 48.
- Mask clearance is 0.1mm, but it should be 0.05mm (see page 10 of ssyz015b).
- Stencil clearance is 0.1mm, but it should be 0 to 0.05mm (see page 10 of ssyz015b). Make it 0.

Note that I got clearances wrong in my MicroStar Junior footprints, and just saw it now when I'm reviewing yours. I'll open a PR to change mask to 0.05mm and stencil to 0mm on the other two.

**Comment by Misca1234** [comment]
I think i got it all now

Texts are aligen around Y = 0,
Renamed it to Texas_MicroStar_Junior_BGA-49_7x7_4.0x4.0mm_Pitch0.5mm
Fixed clearance and stencil

bild

bild

**Comment by evanshultz** [comment]
@Misca1234 
Thanks for updating. Still needs some work:
- F.Fab footprint at 0.2mm in X direction
- F.Fab footprint name and 3D model still call out 49 balls, not 48 balls
- Set F.Paste clearance to 0mm
- Instead of individually setting mask clearance on each pad, use the global setting for all pads:
image

**Comment by Misca1234** [comment]
bild

bild

bild

bild

**Comment by evanshultz** [comment]
@Misca1234 
Thanks!

Just one issue: the description still says 49 balls:
image

Also, may you pull the F.Fab and F.SilkS text closer to the courtyard in the Y direction. They're at -4mm and 4.5mm now, and could go to +/-3.7mm. This will, be default, better associate that text with the footprint. But I'll merge without that.

**Comment by Misca1234** [comment]
I changed the description but the Fab distance I dont understand, it is 4x4 mm

**Comment by SchrodingersGat** [comment]
@Misca1234 

In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
