### PR TITLE
aligning footprints to the new 3D BGA models

### PR DESCRIPTION
**Pull request by easyw**
https://github.com/KiCad/packages3D/Housings_BGA.3dshapes

### CODE REVIEW

**Comment by easyw** [comment]
the remaining errors were already present before this commit

**Comment by SchrodingersGat** [comment]
Hi @easyw as you are touching these (there are only 5 files) can you please add second RefDes to F.Fab layer @ (0,0) with text "%R". That way they will be fully KLC compliant.

**Comment by easyw** [comment]
@SchrodingersGat
 done

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
