### PR TITLE
For BGA case with 0.5mm balls ~0.4mm pads should be used instead

### PR DESCRIPTION
**Pull request by krtkr**
Hi all!

I guess we should change 0.5mm pads to 0.4mm pads for BGA-256. See info below:

"Well a good place to start for questions like these would be the IPC spec PC-7351B not free but it has all the information you'd need about land patterns for most any part."
https://electronics.stackexchange.com/questions/165232/how-to-determine-bga-land-pad-diameter-for-given-ball-diameter

Actual footprint refer to xilinx package documentation. Same (~0.4mm) suggestion is given at Xilinx footprint recommendations:
https://www.xilinx.com/support/documentation/user_guides/ug1099-bga-device-design-rules.pdf

### CODE REVIEW

**Comment by krtkr** [comment]
After more research on the subject it might be reasonable to make two versions of the footprint: with 0.4mm and 0.5mm pads. Though referred package (Xilinx FT256) has 0.5mm balls, some packages might have 0.6mm balls.

What about creating two footprints?

This should be possible in new KLC (see https://github.com/KiCad/kicad-library/issues/1447). I guess we should wait until new KLC ready so we can use proper names for two footprints.

**Comment by SchrodingersGat** [comment]
@evanshultz do you want to weigh in on this one? I have zero BGA experience :)

**Comment by evanshultz** [comment]
@krtkr 
Thanks for bringing this up!

The copper pads should be smaller than the ball diameter. I've never seen any footprint or information otherwise. 80% of the diameter is a good choice, so 0.4mm pads for 0.5mm balls is OK.

We can use the new naming convention now! I believe the new name would be `BGA-256_16x16_17.0x17.0x1.40mm_P1.0mm_Ball0.5mm_Pad0.4mm_NSMD.kicad_mod`? Can you please check that, @SchrodingersGat, and also advise if you want to rename or leave it alone?

Also, the link on this footprint only shows package dimensions so other collateral should be included. Please also add the PDF user guide you mentioned above.

**Comment by SchrodingersGat** [comment]
Pretty much spot on with the naming! Only addition is to add `B` as a prefix for the package body dimensions :)

**Comment by krtkr** [comment]
Hi all!
I did following:
1. Update name according to new KLC.
2. Add Xilinx design rules.

**Comment by SchrodingersGat** [comment]
@krtkr 

In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
