### PR TITLE
add DSBGA-8_Pitch0.5mm_Dia0.25mm.kicad_mod

### PR DESCRIPTION
**Pull request by jjuyon**
Hi,
Here is a new package DSBGA-8_Pitch0.5mm_Dia0.25mm also called YZP (R-XBGA-N8) by Texas Instruments. To use for example with TXB0102YZP
Not sure about the real name of the package

Best,
Julien

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jjuyon very nice symbol :) A couple of small suggestions:

a) Add package dimensions (AxBmm) to the package name as is done for footprints in other `Housings_xx.pretty` libs
b) Make the bevel on the F.Fab layer larger (~0.5mm)

**Comment by jjuyon** [comment]
Hi,
It is done.

Julien

**Comment by SchrodingersGat** [comment]
@jjuyon please use `width`x`height`mm e.g. **_0.9x1.9mm_** for the dimensions :)

**Comment by jkriege2** [comment]
Please also orient on the names already in the lib, like `BGA-9_3x3_1.6x1.6mm_Pitch0.5mm` this is `PACK-PINS_GRIDXxGRIDY_SIZEXxSIZEYmm_PitchPITCHmm` (optionally add Dia)

JAN

**Comment by jjuyon** [comment]
Ok,
It is done

Julien

**Comment by SchrodingersGat** [comment]
@jjuyon thanks for the changes.

Just one more thing, sorry I did not spot this before.

Please expand the silkscreen out such that it will be visible after the component is loaded.

e.g.

capture

**Comment by jkriege2** [comment]
Is the package really beveled? If not, shouldn't the silkscreen be rectangluar (+pin1 mark somewhere outside, e.g. double corner or circle ...), as otherwise the silkscreen is below the package ...
JAN

**Comment by SchrodingersGat** [comment]
Jan is correct. According to latest IPC standards, BGA should be designated like such:

capture

So, here is the adjusted footprint:

bga

Thanks :)

**Comment by jkriege2** [comment]
but then silkscreen is still under the package ... is that a problem?

**Comment by SchrodingersGat** [comment]
Fair point.

I think that the current BGA symbols in this repo are not explicit enough about pin-1.

What do you think of this concept:

capture

**Comment by jkriege2** [comment]
Fine for me --- but we could also have the third corner ... and the circle as mark?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Most other .pretty libs have the pin-1 corner "missing" from silkscreen so that it is obvious which corner is different. 

You will notice that the IPC image I linked above would be "equivalent" to this as the bevelled silkscreen would be invisible (under the footprint)

**Comment by jkriege2** [comment]
fine with me ... you're right ;-)

**Comment by jjuyon** [comment]
Hi,
You are right, the package is not beveled so I did the changes according to the suggestions.

Best,
Julien

**Comment by SchrodingersGat** [comment]
Great work, thanks for making the changes.

**Pull request merged**
