### PR TITLE
added BGA152

### PR DESCRIPTION
**Pull request by nerdyscout**
BGA footprint with 152pins 
grafik

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please add `mm` after the word `Pitch` :)

**Comment by nerdyscout** [comment]
I just recognized the pincount is wrong... i will fix this within the next days.

**Comment by nerdyscout** [comment]
updated version
image

**Comment by SchrodingersGat** [comment]
Have you fixed the pincount already? I guess that 1hr counts as "within the next few days" ;)

**Comment by nerdyscout** [comment]
yes it's done.
As i've noticed the BGA132 was wrong as well I decided to fix both as quick as possible.

**Comment by SchrodingersGat** [comment]
Well, thanks for fixing it :)

**Pull request merged**
