### PR TITLE
added  Texas DBSGA-6 

### PR DESCRIPTION
**Pull request by jkriege2**
- from http://www.ti.com/lit/ds/symlink/ts5a3159a.pdf
- based on the existing DBSGA-8
- KLC-errors are due to pads ... I based this on the existing footprints, if I can improve, let me know how to do them better!
- required for https://github.com/KiCad/kicad-library/pull/1773

2017-10-25 19_15_44-footprint editor no active library

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Is there a particular reason that the stencil apertures are rectangular?

**Comment by jkriege2** [comment]
no ... I just took one existing footprint from that series, removed two pins and moved the whole stuff + did minor adjustments to the outlines ... but I can remove the rectangulars ... I was wondering about them anyways. Is there a best practice for such tiny BGA packages?

cu
JAN

**Comment by SchrodingersGat** [comment]
I don't know enough about these either. 

@evanshultz I believe you made the footprint that this is based on? Can you provide any information on the rectangular pads? Is this a SMD/NSMD thing?

**Comment by evanshultz** [comment]
Just back, and I've missed a lot. It's all in the datasheet: see pages 31-33. You can see that NSMD pads are preferred (due to tighter tolerances as discussed earlier) and the stencil openings are square. We talked before about converting them to squircles when possible, but for now a square/rectangle is as close as we can get.

**Comment by SchrodingersGat** [comment]
Ok, thanks for the reminder Evan. And thanks for the footprint Jan

**Pull request merged**
