### PR TITLE
BGA-132_11x17_12x18mm_Pitch0.5mm

### PR DESCRIPTION
**Pull request by nerdyscout**
BGA132pin package (used eg Micron MT29F128G08CECDBJ4)

image

### CODE REVIEW

**Comment by nerdyscout** [comment]
updated
image

**Comment by SchrodingersGat** [comment]
Please add a pin-1 indicator on the silkscreen layer. To keep it small, you can make a small `L` shape that curves around the top-left corner, with each side ~1.5mm

**Comment by nerdyscout** [comment]
image

**Comment by SchrodingersGat** [comment]
Can you please add some clearance (~0.2mm) between the main silkscreen and the pin-1 indication? The silkscreen lines could be hard to differentiate especially with poor quality silkscreening. Thanks :)

**Comment by nerdyscout** [comment]
image

I updated now as suggested, but I am curious... non of the other footprints in this repo does have a this clearance distance. why not keep it consistent?

**Comment by SchrodingersGat** [comment]
You're right, they should be consistent. I have just pushed a PR which fixes all of the BGA parts accordingly.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution - I forgot to merge it last time

**Pull request merged**
