### PR TITLE
Dsbga 12 maxim wlp texas junior dsbga 12

### PR DESCRIPTION
**Pull request by Misca1234**
Added the foot print 
DSBGA-12_3x4_1.36x1.86mm_Pitch0.5mm_Dia0.25mm.kicad_mod
Texas_Junior_DSBGA-12_4x3_2.5x2.0mm_Pitch0.5mm_Dia0.30mm.kicad_mod
From http://www.ti.com/lit/ds/symlink/txb0104.pdf

and
Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5mm.kicad_mod
From  http://pdfserv.maximintegrated.com/package_dwgs/21-0009.PDF

Correct 3D models will come later

bild

bild

bild

bild

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
DSBGA-12_3x4_1.36x1.86mm_Pitch0.5mm_Dia0.25mm.kicad_mod
There is no 0.25mm diameter option described in the datasheet linked in the footprint.
It looks like the package might fit 0.275 & 0.320 mm diameter (by what i gather from the pad diameter)
I can not find a description about pin placement and package size. Where did you get this information from?

Texas_Junior_DSBGA-12_4x3_2.5x2.0mm_Pitch0.5mm_Dia0.30mm.kicad_mod
I assume this is the package described on page 31 of the linked datsheet.
If this is the case it should be 2.5x2.0mm. => Fab rectangle from (-1.25, -1.0) to (1.25, 1.0)
Yours is 3.5x2mm
Why is your chamfer on the fab outline where it is?

Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5mm.kicad_mod
The average between the maximum sizes given in the datasheet would be 2.035x1.555 (or rounded 2.04x1.56)
You used this sizes for the outline but not in the naming.

**Comment by Misca1234** [comment]
**> DSBGA-12_3x4_1.36x1.86mm_Pitch0.5mm_Dia0.25mm.kicad_mod
> There is no 0.25mm diameter option described in the datasheet linked in the footprint.
> It looks like the package might fit 0.275 & 0.320 mm diameter (by what i gather from the pad diameter)
> I can not find a description about pin placement and package size. Where did you get this information from?**
the _Dia0.25 follows the the nomenclature for the DSBGA-8_2x4_0.9x1.9mm_Pitch0.5mm_Dia0.25mm that was already in the database (easyw/kicad-3d-models-in-freecad) and according to the cq_parameters.py it says it should be "ball pin width diameter with a small extra" and because the medium ball diameter is 0.23 it was set it to 0.25.

The pin placement is in the upper left image on page 24 in http://www.ti.com/lit/ds/symlink/txb0104.pdf
The footprint name was given the same as the 3D model.
According to http://www.ti.com/lit/ds/symlink/txb0102.pdf which have the 8-pin variant in the same "family" , the footprint of the pad is 0.23.
See also 
http://www.ti.com/lit/an/snva009ag/snva009ag.pdf
Chapter 5 PCB Layout

_:I remove the suffix _Dia0.25mm from the name


**Texas_Junior_DSBGA-12_4x3_2.5x2.0mm_Pitch0.5mm_Dia0.30mm.kicad_mod
I assume this is the package described on page 31 of the linked datsheet.
If this is the case it should be 2.5x2.0mm. => Fab rectangle from (-1.25, -1.0) to (1.25, 1.0)
Yours is 3.5x2mm
Why is your chamfer on the fab outline where it is?**

Yes, it is page 31.

_I change it to 2.5x2.0 , fix the chamfer and move out the Pin-1 designator outside the courtyard
and remove the suffix _Dia0.30mm_

**Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5mm.kicad_mod
The average between the maximum sizes given in the datasheet would be 2.035x1.555 (or rounded 2.04x1.56)
You used this sizes for the outline but not in the naming.**
_I rename them_

**Comment by Misca1234** [comment]
Here are the new names and changes

bild

bild

bild

**Comment by Misca1234** [comment]
Instead of the "hook" at pin 1 in F.Silk, shall I change it into a straight line insteadm like for the SO-&L ?


bild

**Comment by Misca1234** [comment]
Shall I remove the foot print size from the name as described by  SchrodingersGat in
https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/43

**Comment by SchrodingersGat** [comment]
If these are truly unique to the particular manufacturer then yes, please conform to that :)

**Comment by Misca1234** [comment]
Changed the names of the WLP and Texas so they don't contain the sizes
Removed the "diam" as suffix to the DSGBA-12 foot print

bild

bild


bild

**Comment by Misca1234** [comment]
Poke

**Comment by poeschlr** [comment]
Texas_Junior_DSBGA-12:

The couryard clearance in x direction is 1.5mm instead of 1mm
I think it would look better if the chamfer is 45 degree.

**Comment by Misca1234** [comment]
Here we go

bild

**Comment by poeschlr** [comment]
Looks good. Thanks.

**Comment by Misca1234** [comment]
Np

**Pull request merged**
