### PR TITLE
Added UFBGA-132 0.5mm Pitch

### PR DESCRIPTION
**Pull request by suzizecat**
Added UFBGA-132 (STM32L4x6Q)
Soldermask clearance is set to 0.05 according to Wurth/ST may be set lower.
Pads are a little bit larger than specified in ST (cf Wurth)

[Würth HDI design guide - Page 5](http://www.we-online.fr/web/fr/index.php/download/media/04_leiterplatte/2011_2/relaunch/produkte_5/microvia_hdi/141030_DesignGuide_HDI_1_1.pdf)
[STM32L4x6Q Datasheet - Page 231](http://www.st.com/content/ccc/resource/technical/document/datasheet/c5/ed/2f/60/aa/79/42/0b/DM00108832.pdf/files/DM00108832.pdf/jcr:content/translations/en.DM00108832.pdf)

I'm not quite sure of myself on this. If you have any suggestion, please feel free to tell me.

Thanks !
Julien

image

image

### CODE REVIEW

**Comment by poeschlr** [comment]
Looks great.
If you could add the datasheet link to the documentation field this pr can be merged. (shows users what has been used to design this footprint)

**Comment by suzizecat** [comment]
I didn't found any file with just the footprint information. I added the STM32L486 DS (230 pages) which contain the reference.

**Comment by poeschlr** [comment]
Looks good. Thanks for your contribution.

**Comment by suzizecat** [comment]
Yay ! Thanks for the review 😄

**Pull request merged**
